#+TITLE: Braindump

Collection of my notes using the Zettelkasten method and [[https://www.orgroam.com/][Org-Roam]].

The braindump is a site generated via [[https://github.com/kaushalmodi/ox-hugo][ox-hugo]] and [[https://gohugo.io/][hugo]], ox-hugo transforms the .org files into .md and hugo uses them to build a webpage.

My setup is pretty much a copy of [[https://github.com/jethrokuan/braindump][Jethrokuan's braindump]] but using a modified theme [[https://github.com/gutofarias/cortex-tex-dark][Cortex-Tex-Dark]].


* Installing instructions.

The installation is comprised into two parts:

** Converting them using ox-hugo

*** Put all files in a folder

*** Run build.py

- Install [[https://ninja-build.org/][ninja]]
  build.py uses ninja in order to convert all files at once. 
  
- Setup your build.py
  I made my so that I only need to change the =mypath= variable. Also maybe the =glob1= or =glob2= variables according to where the folder with the org files is.

- Check the publish.el file
  I changed the file that from Jethrokuan's braindump in order to use an older version of org-roam. Also, I added the =content_path= as a variable. 

- Run build.py

  
** Run hugo

*** Place the config.toml in the root folder

*** Add a theme
Use the config.toml to state which theme are you going to use.

*** Run hugo
In the root folder execute =hugo= in the terminal.

*** hugo server
You can view the generated website by running =hugo server= in the terminal and open the resulting link.


* Considerations

The resulting files from hugo are placed in a folder named /public/. You can separate your core files from the generated hugo files using a submodule. 

I did as in [[https://www.youtube.com/watch?v=LIFvgrRxdt4][https://www.youtube.com/watch?v=LIFvgrRxdt4]] and made two repositories on github, one for the core content and the other for the site generated by hugo. I can run the site using gihub pages.

Also I made a submodule for my theme in order to keep things organized and put it on github ([[https://github.com/gutofarias/cortex-tex-dark][Cortex-Tex-Dark]]).
