#+TITLE: 2021-06-25
#+AUTHOR: João Gutemberg Farias
#+EMAIL: joao.gutemberg.farias@gmail.com
#+ROAM_TAGS: 

- tags ::

* Testando

* Parecer Equiparação ESO - Victor Hugo

 Após análise do processo 23082.007921/2021-79 que trata de um requerimento de Equiparação de ESO do aluno Victor Hugo Nascimento Cleto, foram feitas as seguinte observações em consonância com a Resolução CEPE 425/2010 e respectiva instrução normativa:
 
 1. De acordo com a página 51 do PPC, incluiu-se a possibilidade de equiparação de atividades de extensão e de iniciação científica ao estágio supervisionado.
 2. As atividades a serem equiparadas são atividades de extensão já concluídas pelo aluno com carga horária suficiente.
 3. As atividades são compatíveis com a formação do aluno no curso de Engenharia Mecânica, contendo assuntos abordados em disciplinas das áreas de Mecânica dos Fluidos, Materiais e Projeto de Maquinas.
    
 Diante do exposto, a comissão designada para análise recomenda DEFERIMENTO do pedido.
 
 A comissão foi composta dos seguintes membros:
 - Felipe Orlando Centeno Gonzalez (Presidente)
 - Euclides Apolinário Cabral de Pina
 - João Gutemberg Barbosa de Farias Filho
