#+TITLE: amininan2017 | Explicit Inverse Kinematic Solution for the Industrial FUM Articulated Arm using Dual Quaternion Approach
#+CREATED: [2021-10-07 Thu 16:57]
#+LAST_MODIFIED: [2021-10-07 Thu 18:16]
#+ROAM_KEY: cite:amininan2017
#+ROAM_TAGS: 

The paper solves the [[file:../inverse_kinematics.org][inverse kinematics]] of an specific [[file:../serial_mechanism.org][serial 6dof industrial arm]] using dual quaternions. The [[file:../direct_kinematics.org][direct kinematics]] equations are derived using DQ and through manipulating the equations they can solve it for the inverse kinematics problem. Nothing too fancy or new.

* Info
:PROPERTIES:
:ID: amininan2017
:DOCUMENT_PATH: ../../../Zotero/storage/43DVRGPL/Amininan et al. - 2017 - Explicit Inverse Kinematic Solution for the Indust.pdf
:TYPE: Inproceedings
:AUTHOR: Amininan, E., Sheikhha, F. H., Baghyari, F., Hosseini, S., Najmabadi, M., & Akbarzadeh, A.
:YEAR: 2017
:JOURNAL: 
:DOI:  http://dx.doi.org/10.1109/ICRoM.2017.8466222
:URL: ---
:KEYWORDS: ---
:END:
:ABSTRACT:
The industrial grade FUM articulated arm is a six-axis robot arm, here on referred to as, FUM 6R-20, designed by Ferdowsi University of Mashhad Robotics Lab. In this paper, an explicit inverse kinematics solution for the industrial grade FUM 6R-20 is presented. The dual quaternion, DQ, method is presented. This method uses two quaternions, one for orientation and one for position to represent the kinematics equations of the robot. The DQ method avoids the wrist singularity as a result of the rotation matrices. It is shown that this approach eliminates the wrist singularity and the gimbal lock problem. The Simulink as well as the SolidWorks models of the FUM 6R-20 are also developed. All eight inverse kinematics solutions are obtained. Three random positions and orientations in space are selected and results of the closed-form solutions are verified with the results of both Simulink and SolidWorks software.
:END:

* Notes
:PROPERTIES:
:NOTER_DOCUMENT: ../../../Zotero/storage/43DVRGPL/Amininan et al. - 2017 - Explicit Inverse Kinematic Solution for the Indust.pdf
:NOTER_PAGE: [[pdf:/Users/guto/Sync/Projetos/Zotero/storage/43DVRGPL/Amininan et al. - 2017 - Explicit Inverse Kinematic Solution for the Indust.pdf::6]]
:END:

The paper solves the inverse kinematics of an specific serial 6dof industrial arm using dual quaternions. The direct kinematics equations are derived using DQ and through manipulating the equations they can solve it for the inverse kinematics problem. Nothing too fancy or new.
