#+TITLE: birlescu2020 | Joint-Space Characterization of a Medical Parallel Robot Based on a Dual Quaternion Representation of SE(3)
#+CREATED: [2021-10-13 Wed 15:53]
#+LAST_MODIFIED: [2021-10-13 Wed 16:06]
#+ROAM_KEY: cite:birlescu2020
#+ROAM_TAGS: 

Muito grande. Não li. Só sei que usa os [[file:../study_parameters.org][parâmetros de Study]] e aplica num [[file:../parallel_mechanisms.org][robô médico paralelo]]

* Info
:PROPERTIES:
:ID: birlescu2020
:DOCUMENT_PATH: ../../../Zotero/storage/NWHZ3BTT/Birlescu et al. - 2020 - Joint-Space Characterization of a Medical Parallel.pdf
:TYPE: Article
:AUTHOR: Birlescu, I., Husty, M., Vaida, C., Gherman, B., Tucan, P., & Pisla, D.
:YEAR: 2020
:JOURNAL: Mathematics
:DOI:  http://dx.doi.org/10.3390/math8071086
:URL: ---
:KEYWORDS: ---
:END:
:ABSTRACT:
The paper proposes a mathematical method for redefining motion parameterizations based on the joint-space representation of parallel robots. The study parameters of SE(3) are used to describe the robot kinematic chains, but, rather than directly analyzing the mobile platform motion, the joint-space of the mechanism is studied by eliminating the Study parameters. From the loop equations of the joint-space characterization, new parameterizations are defined, which enable the placement of a mobile frame on any mechanical element within the parallel robot. A case study is presented for a medical parallel robotic system in which the joint-space characterization is achieved and based on a new defined parameterization, the kinematics for displacement, velocities, and accelerations are studied. A numerical simulation is presented for the derived kinematic models, showing how the medical robot guides the medical tool (ultrasound probe) on an imposed trajectory.
:END:

* Notes
:PROPERTIES:
:NOTER_DOCUMENT: ../../../Zotero/storage/NWHZ3BTT/Birlescu et al. - 2020 - Joint-Space Characterization of a Medical Parallel.pdf
:NOTER_PAGE: [[pdf:/Users/guto/Sync/Projetos/Zotero/storage/NWHZ3BTT/Birlescu et al. - 2020 - Joint-Space Characterization of a Medical Parallel.pdf::1]]
:END:

** Resumo
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/NWHZ3BTT/Birlescu et al. - 2020 - Joint-Space Characterization of a Medical Parallel.pdf::1++0.91;;annot-1-18]]
:ID:       ../../../Zotero/storage/NWHZ3BTT/Birlescu et al. - 2020 - Joint-Space Characterization of a Medical Parallel.pdf-annot-1-18
:END:

Muito grande. Não li. Só sei que usa os [[file:../study_parameters.org][parâmetros de Study]] e aplica num [[file:../parallel_mechanisms.org][robô médico paralelo]]
