#+TITLE: bultmann2019 | Stereo Visual SLAM Based on Unscented Dual Quaternion Filtering
#+CREATED: [2021-09-22 Wed 15:43]
#+LAST_MODIFIED: [2021-09-22 Wed 17:02]
#+ROAM_KEY: cite:bultmann2019
#+ROAM_TAGS: 

[[file:../simultaneous_localization_and_mapping_slam.org][SLAM]] using an DQ unscented filter and using the stero visual data.
N達o tenho muito a dizer porque n達o li muito.

* Info
:PROPERTIES:
:ID: bultmann2019
:DOCUMENT_PATH: ../../../Zotero/storage/R28QNCAP/Bultmann et al. - Stereo Visual SLAM Based on Unscented Dual Quatern.pdf
:TYPE: Article
:AUTHOR: Bultmann, S., Li, K., & Hanebeck, U. D.
:YEAR: 2019
:JOURNAL: 
:DOI: ---
:URL: ---
:KEYWORDS: ---
:END:
:ABSTRACT:
We present DQV-SLAM (Dual Quaternion Visual SLAM). This novel feature-based stereo visual SLAM framework uses a stochastic filter based on the unscented transform and a progressive Bayes update, avoiding linearization of the nonlinear spatial transformation group. 6-DoF poses are represented by dual quaternions where rotational and translational components are stochastically modeled by Bingham and Gaussian distributions. Maps represented by point clouds of ORB-features are incrementally built and landmarks are updated with an unscented transform-based method. In order to get reliable measurements during the update, an optical flow-based approach is proposed to remove false feature associations. Drift is corrected by pose graph optimization once loop closure is detected. The KITTI and EuRoC datasets for stereo setup are used for evaluation. The performance of the proposed system is comparable to stateof-the-art optimization-based SLAM systems and better than existing filtering-based approaches.
:END:

* Notes
:PROPERTIES:
:NOTER_DOCUMENT: ../../../Zotero/storage/R28QNCAP/Bultmann et al. - Stereo Visual SLAM Based on Unscented Dual Quatern.pdf
:NOTER_PAGE: [[pdf:/Users/guto/Sync/Projetos/Zotero/storage/R28QNCAP/Bultmann et al. - Stereo Visual SLAM Based on Unscented Dual Quatern.pdf::1]]
:END:
** Resumo
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/R28QNCAP/Bultmann et al. - Stereo Visual SLAM Based on Unscented Dual Quatern.pdf::1++0.00;;annot-1-0]]
:ID:       ../../../Zotero/storage/R28QNCAP/Bultmann et al. - Stereo Visual SLAM Based on Unscented Dual Quatern.pdf-annot-1-0
:END:

SLAM using an DQ unscented filter and using the stero visual data.
N達o tenho muito a dizer porque n達o li muito.
