#+TITLE: dong2019 | Partial Lyapunov Strictification: Dual-Quaternion-Based Observer for 6-DOF Tracking Control
#+CREATED: [2021-09-23 Thu 11:34]
#+LAST_MODIFIED: [2021-09-23 Thu 16:08]
#+ROAM_KEY: cite:dong2019
#+ROAM_TAGS: 

The authors develop a Dual Quaternion based 6-DOF observer and controller. The controller has a PD-like structure. The observer and controller are validated through simulation of a spacecraft in absensce of both translational and angular velocity measurements.

* Info
:PROPERTIES:
:ID: dong2019
:DOCUMENT_PATH: ../../../Zotero/storage/ID55FW8Q/Dong et al. - 2019 - Partial Lyapunov Strictification Dual-Quaternion-.pdf
:TYPE: Article
:AUTHOR: Dong, H., Hu, Q., Akella, M. R., & Mazenc, F.
:YEAR: 2019
:JOURNAL: IEEE Trans. Contr. Syst. Technol.
:DOI:  http://dx.doi.org/10.1109/TCST.2018.2864723
:URL: ---
:KEYWORDS: ---
:END:
:ABSTRACT:
Based on the dual-quaternion description, a smooth six-degree-of-freedom observer is proposed to estimate the incorporating linear (translational) and angular velocity, called the dual-angular velocity, for rigid bodies. To establish the observer, some important properties of dual vectors and dual quaternions are presented and proved, additionally, the kinematics of dualtransformation matrices is deduced, and the transition relationship between dual quaternions and dual transformation matrices is subsequently analyzed. An important feature of the observer is that all estimation states are ensured to be C{$infty$} continuous, and estimation errors are shown to exhibit asymptotic convergence if the signals to be estimated are bounded. Furthermore, to achieve tracking control objectives, the proposed observer is combined with an independently designed proportional-derivative-like feedback control law (using full-state feedback), and a special Lyapunov ``strictification'' process is employed to ensure a separation property between the observer and the controller, which further guarantees almost global asymptotic stability of the closed-loop tracking error dynamics. Numerical simulation results for a prototypical spacecraft pose tracking mission application are presented to illustrate the effectiveness and robustness of the proposed method.
:END:

* Notes
:PROPERTIES:
:NOTER_DOCUMENT: ../../../Zotero/storage/ID55FW8Q/Dong et al. - 2019 - Partial Lyapunov Strictification Dual-Quaternion-.pdf
:NOTER_PAGE: [[pdf:/Users/guto/Sync/Projetos/Zotero/storage/ID55FW8Q/Dong et al. - 2019 - Partial Lyapunov Strictification Dual-Quaternion-.pdf::1]]
:END:

** Resumo
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/ID55FW8Q/Dong et al. - 2019 - Partial Lyapunov Strictification Dual-Quaternion-.pdf::1++0.00;;annot-1-3]]
:ID:       ../../../Zotero/storage/ID55FW8Q/Dong et al. - 2019 - Partial Lyapunov Strictification Dual-Quaternion-.pdf-annot-1-3
:END:

The authors develop a Dual Quaternion based 6-DOF observer and controller. The controller has a PD-like structure. The observer and controller are validated through simulation of a spacecraft in absensce of both translational and angular velocity measurements.
