#+TITLE: oh_study_2017 | Study on Robot Trajectory Planning by Robot End-Effector Using Dual Curvature Theory of the Ruled Surface
#+CREATED: [2021-07-07 Wed 11:51]
#+LAST_MODIFIED: [2021-07-16 Fri 17:14]
#+ROAM_KEY: cite:oh_study_2017
#+ROAM_TAGS: 

- tags :: [[file:../dual_quaternions_applications.org][Dual Quaternions Applications]]
  
The work describes the trajectory of the robot's end effector by using [[file:../differential_geometry.org][Differential Geometry]] and [[file:../dual_curvature_theory.org][Dual Curvature Theory]] instead of [[file:../motion_interpolation.org][Motion Interpolation]]. The author claims that it makes the expressions simpler and intuitive.

* Info 
:PROPERTIES:
:ID: oh_study_2017
:DOCUMENT_PATH: ../../../Zotero/storage/6W49F5MJ/Oh et al. - 2017 - Study on Robot Trajectory Planning by Robot  End-E.pdf
:TYPE: Article
:AUTHOR: Oh, Y. S., Abhishesh, P., & Ryuh, B. S.
:YEAR: 2017
:JOURNAL: International Journal of Mechanical and Materials Engineering
:DOI: ---
:URL: ---
:KEYWORDS: nlido
:VISIBILITY: folded
:END:
:ABSTRACT:
This paper presents the method of trajectory planning by the robot end-effector which accounts for more accurate and smooth differential geometry of the ruled surface generated by tool line fixed with end-effector based on the methods of curvature theory of ruled surface and the dual curvature theory, and focuses on the underlying relation to unite them for enhancing the efficiency for trajectory planning. Robot motion can be represented as motion properties of the ruled surface generated by trajectory of the Tool Center Point (TCP). The linear and angular properties of the six degree-of-freedom motion of end-effector are computed using the explicit formulas and functions from curvature theory and dual curvature theory. This paper explains the complete dualization of ruled surface and shows that the linear and angular motion applied using the method of dual curvature theory is more accurate and less complex.
:END:

* Notes
:PROPERTIES:
:NOTER_DOCUMENT: ../../../Zotero/storage/6W49F5MJ/Oh et al. - 2017 - Study on Robot Trajectory Planning by Robot  End-E.pdf
:NOTER_PAGE: [[pdf:/Users/guto/Sync/Projetos/Zotero/storage/6W49F5MJ/Oh et al. - 2017 - Study on Robot Trajectory Planning by Robot  End-E.pdf::6]]
:VISISIBILITY: folded
:END:

** Resumo
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/6W49F5MJ/Oh et al. - 2017 - Study on Robot Trajectory Planning by Robot  End-E.pdf::1++0.00;;annot-1-2]]
:ID:       ../../../Zotero/storage/6W49F5MJ/Oh et al. - 2017 - Study on Robot Trajectory Planning by Robot  End-E.pdf-annot-1-2
:VISIBILITY: folded
:END:

The work describes the trajectory of the robot's end effector by using [[file:../differential_geometry.org][Differential Geometry]] and [[file:../dual_curvature_theory.org][Dual Curvature Theory]] instead of [[file:../motion_interpolation.org][Motion Interpolation]]. The author claims that it makes the expressions simpler and intuitive.

** Nota 1
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/6W49F5MJ/Oh et al. - 2017 - Study on Robot Trajectory Planning by Robot  End-E.pdf::1++8.75;;annot-1-3]]
:ID:       ../../../Zotero/storage/6W49F5MJ/Oh et al. - 2017 - Study on Robot Trajectory Planning by Robot  End-E.pdf-annot-1-3
:END:

Exemplifies the [[file:../path_planning.org][Path Planning]] as being constructed by some data points and [[file:../motion_interpolation.org][Motion Interpolation]].
** Nota 2
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/6W49F5MJ/Oh et al. - 2017 - Study on Robot Trajectory Planning by Robot  End-E.pdf::1++0.24;;annot-1-4]]
:ID:       ../../../Zotero/storage/6W49F5MJ/Oh et al. - 2017 - Study on Robot Trajectory Planning by Robot  End-E.pdf-annot-1-4
:END:

Defines [[file:../ruled_surface.org][Ruled Surface]] as a trajectory made when a line moves in space.

