#+TITLE: pham2018 | Set-point control of robot end-effector pose using dual quaternion feedback
#+CREATED: [2021-09-14 Tue 15:47]
#+LAST_MODIFIED: [2021-09-14 Tue 18:36]
#+ROAM_KEY: cite:pham2018
#+ROAM_TAGS: 

The paper implements a [[file:../set_point_controller.org][set-point controller]] for an industrial 6DOF robot using Dual Quaternions. The authors computes the [[file:../direct_kinematics.org][direct kinematics]] using DQ and [[file:../differential_kinematics.org][differential kinematics]] using DQ as vectors in R8. The error equation is manipulated in order to obtain a matrix times a variable, but the matrix represents the system dynamics. This matrix is then writen in Laplace Domain and becomes a [[file:../transference_matrix.org][Transference Matrix]], so Classic Control techniques can be used. Using this approach, two different control laws are generated using the [[file:../jacobian_matrix.org][Jacobian Matrix]] (which are compared). The authors state that the proposed controllers does not have the best performance, compared to more sophisticated controllers, but it is simple to implement and using Laplace it is possible to tune the controller using dynamic system parameteres as damping factor and natural frequency.

Also, the proposed controller is tested using DQ and HTM. The result is that the DQ controller is almost twice as fast to compute.

* Info
:PROPERTIES:
:ID: pham2018
:DOCUMENT_PATH: ../../../Zotero/storage/4FM7NP4G/Pham et al. - 2018 - Set-point control of robot end-effector pose using.pdf
:TYPE: Article
:AUTHOR: Pham, H., Adorno, B., Perdereau, V., & Fraisse, P.
:YEAR: 2018
:JOURNAL: Robotics and Computer-Integrated Manufacturing
:DOI:  http://dx.doi.org/10.1016/j.rcim.2017.11.003
:URL: ---
:KEYWORDS: ---
:ABSTRACT: ---
:END:

* Notes
:PROPERTIES:
:NOTER_DOCUMENT: ../../../Zotero/storage/4FM7NP4G/Pham et al. - 2018 - Set-point control of robot end-effector pose using.pdf
:NOTER_PAGE: [[pdf:/Users/guto/Sync/Projetos/Zotero/storage/4FM7NP4G/Pham et al. - 2018 - Set-point control of robot end-effector pose using.pdf::7]]
:END:
** Resumo
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/4FM7NP4G/Pham et al. - 2018 - Set-point control of robot end-effector pose using.pdf::1++0.00;;annot-1-23]]
:ID:       ../../../Zotero/storage/4FM7NP4G/Pham et al. - 2018 - Set-point control of robot end-effector pose using.pdf-annot-1-23

O trabalho implementa um controlador de set-point (não trajetória) para um robô industrial 6dof usando quatérnios duais. É proposto um cálculo de cinemática usando DQ e um cálculo da cinemática diferencial usando vetores no R8. A equação do erro é trabalhada para ficar como uma matriz que multiplica uma variável, sendo que a matriz representa a dinâmia do robô. Essa matriz é trabalhada no domínio de Laplace e é dita uma matriz de transferência, abrindo margem para usar técnicas de controle clássico. A partir disso são geradas duas leis de controle diferentes baseadas na matriz Jacobiana (que são posteriormente comparadas). O autor diz que o controlador não tem a melhor performance (quando comparado com controladores mais sofisticados) mas é simples de se implementar e com a abordagem usando Laplace é possível relacionar parâmetros desejados (como fator de amortecimento e frequência natural) para tunar o controlador.

:END:

O trabalho implementa um controlador de set-point (não trajetória) para um robô industrial 6dof usando quatérnios duais. É proposto um cálculo de cinemática usando DQ e um cálculo da cinemática diferencial usando vetores no R8. A equação do erro é trabalhada para ficar como uma matriz que multiplica uma variável, sendo que a matriz representa a dinâmia do robô. Essa matriz é trabalhada no domínio de Laplace e é dita uma matriz de transferência, abrindo margem para usar técnicas de controle clássico. A partir disso são geradas duas leis de controle diferentes baseadas na matriz Jacobiana (que são posteriormente comparadas). O autor diz que o controlador não tem a melhor performance (quando comparado com controladores mais sofisticados) mas é simples de se implementar e com a abordagem usando Laplace é possível relacionar parâmetros desejados (como fator de amortecimento e frequência natural) para tunar o controlador.

** Nota pag 3
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/4FM7NP4G/Pham et al. - 2018 - Set-point control of robot end-effector pose using.pdf::3++5.35;;annot-3-10]]
:ID:       ../../../Zotero/storage/4FM7NP4G/Pham et al. - 2018 - Set-point control of robot end-effector pose using.pdf-annot-3-10
:END:

Quatérnios duais podem passar facilmente do seu espaço próprio para um espaço vetorial em R8. Deixando-os propenso a trabalhar muito bem com pose (DQ) e com cinemática diferencial (R8).
** pag 5
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/4FM7NP4G/Pham et al. - 2018 - Set-point control of robot end-effector pose using.pdf::5++3.85;;annot-5-34]]
:ID:       ../../../Zotero/storage/4FM7NP4G/Pham et al. - 2018 - Set-point control of robot end-effector pose using.pdf-annot-5-34
:END:

Interessante essa estratégia de deixar o erro em forma vetorial multiplicado à esquerda por uma matriz de forma a gerar uma matriz de transferência. 
Acho que uma matriz de transferência talvez seja uma matriz de funções de transferência.
** pag 7
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/4FM7NP4G/Pham et al. - 2018 - Set-point control of robot end-effector pose using.pdf::7++10.96;;annot-7-17]]
:ID:       ../../../Zotero/storage/4FM7NP4G/Pham et al. - 2018 - Set-point control of robot end-effector pose using.pdf-annot-7-17
:END:

Comparação entre DQ e HTM no cálculo do controlador mostra DQ como sendo em média pouco menos de duas vezes mais rápido.
