#+TITLE: silva2018 | Whole-body Control of a Mobile Manipulator Using Feedback Linearization and Dual Quaternion Algebra
#+CREATED: [2021-10-14 Thu 11:41]
#+LAST_MODIFIED: [2021-10-15 Fri 11:28]
#+ROAM_KEY: cite:silva2018
#+ROAM_TAGS: 

The papers proposes a [[file:../whole_body_control.org][whole-body control]] using [[file:../feedback_linearization.org][Feedback Linearization]] in a DQ framework. Experiments are made using a nonholonomic mobile ground vehicle with 5-DOF [[file:../serial_mechanism.org][manipulator arm]].

* Info
:PROPERTIES:
:ID: silva2018
:DOCUMENT_PATH: ../../../Zotero/storage/DDGG9WUZ/Silva e Adorno - 2018 - Whole-body Control of a Mobile Manipulator Using F.pdf
:TYPE: Article
:AUTHOR: Silva, F. F. A., & Adorno, B. V.
:YEAR: 2018
:JOURNAL: J Intell Robot Syst
:DOI:  http://dx.doi.org/10.1007/s10846-017-0686-3
:URL: ---
:KEYWORDS: ---
:END:
:ABSTRACT:
This paper presents the whole-body control of a nonholonomic mobile manipulator using feedback linearization and dual quaternion algebra. The controller, whose reference is a unit dual quaternion representing the desired end-effector pose, acts as a dynamic trajectory generator for the end-effector, and input signals for both nonholonomic mobile base and manipulator arm are generated by using the pseudoinverse of the whole-body Jacobian matrix. In order to deal with the nonholonomic constraints, the input signal to the mobile base generated by the wholebody motion control is properly remapped to ensure feasibility. The Lyapunov stability for the proposed controller is presented and experimental results on a real platform are performed in order to compare the proposed scheme to a traditional classic whole-body linear kinematic controller. The results show that, for similar convergence rate, the nonlinear controller is capable of generating smoother movements while having lower control effort than the linear controller.
:END:

* Notes
:PROPERTIES:
:NOTER_DOCUMENT: ../../../Zotero/storage/DDGG9WUZ/Silva e Adorno - 2018 - Whole-body Control of a Mobile Manipulator Using F.pdf
:NOTER_PAGE: [[pdf:/Users/guto/Sync/Projetos/Zotero/storage/DDGG9WUZ/Silva e Adorno - 2018 - Whole-body Control of a Mobile Manipulator Using F.pdf::4]]
:END:

** Resumo
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/DDGG9WUZ/Silva e Adorno - 2018 - Whole-body Control of a Mobile Manipulator Using F.pdf::1++0.00;;annot-1-11]]
:ID:       ../../../Zotero/storage/DDGG9WUZ/Silva e Adorno - 2018 - Whole-body Control of a Mobile Manipulator Using F.pdf-annot-1-11
:END:

The papers proposes a whole-body control using Feedback Linearization in a DQ framework. Experiments are made using a nonholonomic mobile ground vehicle with 5-DOF manipulator arm.
