#+TITLE: sveier2020 | Dual Quaternion Particle Filtering for Pose Estimation
#+CREATED: [2021-09-23 Thu 16:30]
#+LAST_MODIFIED: [2021-09-23 Thu 17:49]
#+ROAM_KEY: cite:sveier2020
#+ROAM_TAGS: 

The authors develop a Dual Quaternion [[file:../particle_filter.org][Particle Filter]] and test it in the [[file:../pose_estimation.org][pose estimation]] of a hanging payload using point clouds data from a Kinect. The pose estimation is then validated showing accurate results.

* Info
:PROPERTIES:
:ID: sveier2020
:DOCUMENT_PATH: ../../../Zotero/storage/N97LXV3E/Sveier e Egeland - 2020 - Dual Quaternion Particle Filtering for Pose Estima.pdf
:TYPE: Article
:AUTHOR: Sveier, A., & Egeland, O.
:YEAR: 2020
:JOURNAL: IEEE Trans. Contr. Syst. Technol.
:DOI:  http://dx.doi.org/10.1109/TCST.2020.3026926
:URL: ---
:KEYWORDS: ---
:END:
:ABSTRACT:
This article presents a particle filter for pose estimation using unit dual quaternion kinematics. The eight-parameter unit dual quaternion is used for global representation of the pose, whereas the six parameters of the dual modified Rodrigues parameters (MRPs) are used for local pose representation in the state-space model. The dual MRPs enable estimates of the mean and the covariance to be calculated from the particles without violating the algebraic constraint of the unit dual quaternion. For verification of the filter and comparison with state of the art, we consider pose measurements available in the form of unit dual quaternions. Angular velocity and specific force measurements from a body-mounted inertial measurement unit are also considered in the filtering. We show through simulations that the suggested particle filter has comparable accuracy with a previously proposed unscented Kalman filter based on unit dual quaternions. We also consider a practical application where the pose of an arbitrary rigid object is estimated using a sequence of point clouds from a 3-D camera. A model point cloud of the object is displaced with the unit dual quaternion associated with each particle, and a fitting score is calculated between the displaced model point cloud and the measured point cloud from the 3-D camera. The likelihoods of the fitting scores are calculated from an exponential distribution and are used to update the weights of the particles. The system was verified in an experiment where the motion of a swinging payload hanging from a crane was estimated using a 3-D camera.
:END:

* Notes
:PROPERTIES:
:NOTER_DOCUMENT: ../../../Zotero/storage/N97LXV3E/Sveier e Egeland - 2020 - Dual Quaternion Particle Filtering for Pose Estima.pdf
:NOTER_PAGE: [[pdf:/Users/guto/Sync/Projetos/Zotero/storage/N97LXV3E/Sveier e Egeland - 2020 - Dual Quaternion Particle Filtering for Pose Estima.pdf::1]]
:END:

** Resumo
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/N97LXV3E/Sveier e Egeland - 2020 - Dual Quaternion Particle Filtering for Pose Estima.pdf::1++0.00;;annot-1-2]]
:ID:       ../../../Zotero/storage/N97LXV3E/Sveier e Egeland - 2020 - Dual Quaternion Particle Filtering for Pose Estima.pdf-annot-1-2
:END:

The authors develop a Dual Quaternion [[file:../particle_filter.org][Particle Filter]] and test it in the [[file:../pose_estimation.org][pose estimation]] of a hanging payload using point clouds data from a Kinect. The pose estimation is then validated showing accurate results.
