#+TITLE: valverde2018 | Dual Quaternion Framework for Modeling of Spacecraft-Mounted Multibody Robotic Systems
#+CREATED: [2021-10-14 Thu 11:25]
#+LAST_MODIFIED: [2021-10-14 Thu 11:35]
#+ROAM_KEY: cite:valverde2018
#+ROAM_TAGS: 

The work describes an framework to derive the dynamics of a satellite, but it can be used to a general serial mechanism (at least I think), the proposed framework works with revolute, prismatic, cylindrical, spherical and planar joints. The equations are computed using dual quaternions and [[file:../newton_euler_method.org][Newton-Euler formulation]].

* Info
:PROPERTIES:
:ID: valverde2018
:DOCUMENT_PATH: ../../../Zotero/storage/LMZ9Q899/Valverde e Tsiotras - 2018 - Dual Quaternion Framework for Modeling of Spacecra.pdf
:TYPE: Article
:AUTHOR: Valverde, A., & Tsiotras, P.
:YEAR: 2018
:JOURNAL: Front. Robot. AI
:DOI:  http://dx.doi.org/10.3389/frobt.2018.00128
:URL: ---
:KEYWORDS: ---
:END:
:ABSTRACT:
This paper lays out a framework to model the kinematics and dynamics of a rigid spacecraft-mounted multibody robotic system. The framework is based on dual quaternion algebra, which combines rotational and translational information in a compact representation. Based on a Newton-Euler formulation, the proposed framework sets up a system of equations in which the dual accelerations of each of the bodies and the reaction wrenches at the joints are the unknowns. Five different joint types are considered in this framework via simple changes in certain mapping matrices that correspond to the joint variables. This differs from previous approaches that require the addition of extra terms that are joint-type dependent, and which decouple the rotational and translational dynamics.
:END:

* Notes
:PROPERTIES:
:NOTER_DOCUMENT: ../../../Zotero/storage/LMZ9Q899/Valverde e Tsiotras - 2018 - Dual Quaternion Framework for Modeling of Spacecra.pdf
:NOTER_PAGE: [[pdf:/Users/guto/Sync/Projetos/Zotero/storage/LMZ9Q899/Valverde e Tsiotras - 2018 - Dual Quaternion Framework for Modeling of Spacecra.pdf::1]]
:END:

** Resumo
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/Sync/Projetos/Zotero/storage/LMZ9Q899/Valverde e Tsiotras - 2018 - Dual Quaternion Framework for Modeling of Spacecra.pdf::1++0.00;;annot-1-24]]
:ID:       ../../../Zotero/storage/LMZ9Q899/Valverde e Tsiotras - 2018 - Dual Quaternion Framework for Modeling of Spacecra.pdf-annot-1-24
:END:

The work describes an framework to derive the dynamics of a satellite, but it can be used to a general serial mechanism (at least I think), the proposed framework works with revolute, prismatic, cylindrical, spherical and planar joints. The equations are computed using dual quaternions and Newton-Euler formulation.
