#+TITLE: Difference of the approach to Dynamics on the Kinematic Analysis - Davies Method for Dynamics
#+AUTHOR: João Gutemberg Farias
#+EMAIL: joao.gutemberg.farias@gmail.com
#+CREATED: [2022-03-09 Wed 12:37]
#+LAST_MODIFIED: [2022-03-09 Wed 12:47]
#+ROAM_TAGS: 

Check out [[file:understanding_davies_method_s_kinematic_analysis.org][Understanding Davies Method's kinematic analysis]] first. 

To deal with dynamics, we can not reference the origin of the system, we need to reference the center of mass of each of the links. Also, we can not make a [[file:closed_kinematic_chain.org][Closed Kinematic Chain]] equation, as the kinematics of a link depends only on the previous joints, not on the next ones.

So in order to compute the kinematics of a link we use the the [[file:coupling_graph.org][Coupling Graph]] and make a graph trajectory going from the [[file:base_link.org][base link]] (origin of the system) to the link whose kinematics we are calculating. We take into account all the joints in this trajectory.

Going through each joint we are summing up the [[file:twist.org][twists]] of the joint relative to the center of mass of the link. The result is the kinematics of link's center of mass, which is the information we need in a Dynamics analysis.

When dealing with a [[file:closed_kinematic_chain_system.org][Closed Kinematic Chain System]], there is more than one trajectory to get from the [[file:base_link.org][Base Link]] to the link whose kinematics we are calculating. We choose one trajectory and use it. The ambiguity will be taken care of after when we analyse the relations between the joints.
