#+TITLE: Inertia
#+AUTHOR: João Gutemberg Farias
#+EMAIL: joao.gutemberg.farias@gmail.com
#+CREATED: [2021-09-29 Wed 11:03]
#+LAST_MODIFIED: [2021-09-29 Wed 11:23]
#+ROAM_TAGS: ideas

Eu não sei se a matriz de inércia é mal compreendida ou se sou eu que não entendo direito. Claro que entendo que tem a ver com como a massa é distribuída, mas mesmo assim parece algo um tanto quanto misterioso.

A idéia aqui é tentar entender a matriz de inércia fazendo uma analogia com o que o operador $m \, d/d\varepsilon$ faz com um vetor de velocidade linear, isto é, transforma de uma grandeza de [[file:pure_vector.org][Pure Vector]] para uma grandeza de [[file:line_vector.org][Line Vector]]. A matriz de inércia faz o contrário, transforma uma grandeza de um vetor linha para um vetor puro.

No caso do operador da massa, podemos racionalizar dizendo que uma velocidade linear é um vetor puro, mas quando é associado a uma massa ganha uma noção de posição no espaço, se transformando num vetor linha. Como seria isso em termos da matriz de inércia.

