#+TITLE: Loss of continuity in mobile frames - Davies Method for Dynamics
#+AUTHOR: João Gutemberg Farias
#+EMAIL: joao.gutemberg.farias@gmail.com
#+CREATED: [2022-03-08 Tue 18:39]
#+LAST_MODIFIED: [2022-03-08 Tue 18:39]
#+ROAM_TAGS: 

No caso de um guindaste a lança é articulada mas o cabo vai sempre na direção da gravidade.
Isso causa um quebra na continuidade, porque apesar de eu poder mover a lança, isso não muda a direção do cabo que vem posterior. O referencial do cabo é independente dos referenciais anteriores.

Tinha descrito uma opção de quebra de continuidade, onde quando ocorresse a quebra, a próxima velocidade dual seria da soma do elo anterior com um acréscimo de um termo novo. Isso faz sentido em termos de velocidade linear, pois no caso de uma corda, ele teria a velocidade linear que está na ponta da lança.

O mesmo não faz tanto sentido para o caso da velocidade angular, já que a velocidade angular da corda não é herdada da lança.

Por isso pensei mais e tou mais propenso a não tratar isso como um caso especial. Tou achando que seria mais coerente modelar a junção entre a corda e a lança como uma junta esférica passiva. Teria que analisar mais para ver se faria sentido.
